#ifndef PROJECT_LV_CONF_OVERRIDE_H
#define PROJECT_LV_CONF_OVERRIDE_H

#include "C:/Users/thswo/Documents/Arduino/libraries/lv_conf.h"

#undef LV_FONT_MONTSERRAT_20
#define LV_FONT_MONTSERRAT_20 1

#undef LV_FONT_MONTSERRAT_24
#define LV_FONT_MONTSERRAT_24 1

#undef LV_FONT_MONTSERRAT_28
#define LV_FONT_MONTSERRAT_28 1

#undef LV_FONT_MONTSERRAT_32
#define LV_FONT_MONTSERRAT_32 1

#undef LV_FONT_MONTSERRAT_40
#define LV_FONT_MONTSERRAT_40 1

#undef LV_FONT_MONTSERRAT_48
#define LV_FONT_MONTSERRAT_48 1

#endif
